"""
Django settings for accounting_app project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1ag&$bm$tul54vl@#j#!8i^+=4*cy0#i(lb4&dt+)!$(o29b3t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django_extensions',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'accounting_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [],
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # This tells Django to look in /templates/
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'accounting_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'kameet_db',
        'USER': 'employee',
        'PASSWORD':'kameet@a1',
        'HOST': '192.168.29.151',
        'PORT':'3306'
    },
    'fy_2024_25': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'kameet_2024_25',
        'USER': 'employee',
        'PASSWORD': 'kameet@a1',
        'HOST': '192.168.29.151',
        'PORT': '3306',
    },
    'fy_2025_26': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'kameet_2025_26',
        'USER': 'employee',
        'PASSWORD': 'kameet@a1',
        'HOST': '192.168.29.151',
        'PORT': '3306',
    },
     'fy_2026_27': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'kameet_2026_27',
        'USER': 'employee',
        'PASSWORD': 'kameet@a1',
        'HOST': '192.168.29.151',
        'PORT': '3306',
    },
     'fy_2027_28': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'kameet_2027_28',
        'USER': 'employee',
        'PASSWORD': 'kameet@a1',
        'HOST': '192.168.29.151',
        'PORT': '3306',
    },
     'fy_2028_29': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'kameet_2028_29',
        'USER': 'employee',
        'PASSWORD': 'kameet@a1',
        'HOST': '192.168.29.151',
        'PORT': '3306',
    },
     'fy_2029_30': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'kameet_2029_30',
        'USER': 'employee',
        'PASSWORD': 'kameet@a1',
        'HOST': '192.168.29.151',
        'PORT': '3306',
    },
  
}



# year wise database routing
DATABASE_ROUTERS = ['routers.yearwise_router.YearwiseRouter']


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'kameet_db',
#         'USER': 'kameet_user',
#         'PASSWORD': 'kameet@a1',
#         'HOST':'192.168.29.110',  # ✅ no space before IP
#         'PORT': '3306',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# BASE_DIR = Path(__file__).resolve().parent.parent
# STATIC_URL = 'static/'
# MEDIA_URL = '/media/'
# MEDIA_ROOT = 'Z:/Kameet Soft Project/accounting_app/media'
# DEBUG = True

import os
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_URL = 'static/'
MEDIA_ROOT = r'Z:\Kameet Soft Project\Bank Statement'
MEDIA_URL = '/media/'

# MEDIA_ROOT = BASE_DIR / 'media'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# open folder location
import os
LAUNCHER_SCRIPT_ROOT = os.path.join(BASE_DIR, 'launcher_scripts')


# pdf_exctract file length settings
DATA_UPLOAD_MAX_NUMBER_FIELDS = 50000



# # Gmail OAuth files
# import os

# # OAuth client you download in step 3
# GMAIL_CLIENT_SECRETS_FILE = os.path.join(BASE_DIR, "credentials.json")

# # where per-account tokens will be stored (outside accounts/)
# GMAIL_TOKEN_DIR = os.path.join(BASE_DIR, "gmail_tokens")

# # time settings
# USE_TZ = True
# TIME_ZONE = "Asia/Kolkata"



# LAN Access
ALLOWED_HOSTS = ["127.0.0.1", "localhost", "192.168.29.151"]

# One common password for modifying master records (Client / Account / Group)
MODIFY_PASSWORD = "moddify_password"

