# Generated by Django 5.2.1 on 2025-06-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=20, unique=True)),
                ('client_name', models.CharField(max_length=100)),
                ('legal_name', models.CharField(max_length=100)),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField()),
                ('other_info', models.TextField(blank=True, null=True)),
                ('pan', models.CharField(max_length=10)),
                ('gst_no', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('file_no', models.CharField(blank=True, max_length=20, null=True)),
                ('busy_code', models.CharField(blank=True, max_length=20, null=True)),
                ('return_types', models.CharField(choices=[('IT', 'Income Tax'), ('GST', 'GST'), ('TDS', 'TDS'), ('TCS', 'TCS')], max_length=50)),
            ],
        ),
    ]
