# Generated by Django 5.2.1 on 2025-06-04 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_client_return_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(blank=True, max_length=20)),
                ('client_name', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=100)),
                ('account_group', models.CharField(max_length=100)),
                ('data_entry', models.CharField(choices=[('Manual', 'Manual'), ('Auto', 'Auto')], default='Manual', max_length=20)),
                ('acc_mail_id', models.EmailField(blank=True, max_length=254)),
                ('account_no', models.CharField(max_length=50)),
                ('two_match', models.CharField(blank=True, max_length=50)),
                ('full_match', models.BooleanField(default=False)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('acc_type', models.CharField(blank=True, choices=[('Saving', 'Saving'), ('Current', 'Current')], max_length=20)),
                ('e_statement', models.BooleanField(default=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('pw', models.CharField(blank=True, max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('contact_no', models.CharField(blank=True, max_length=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
            ],
        ),
    ]
