# Generated by Django 5.2.1 on 2025-06-04 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbank',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.client', to_field='client_id'),
        ),
    ]
