# Generated by Django 5.2.1 on 2025-06-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accountbank_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=20, unique=True)),
                ('group_name', models.CharField(max_length=100)),
                ('group_email', models.EmailField(max_length=254)),
                ('group_phno', models.CharField(max_length=15)),
            ],
        ),
    ]
