# Generated by Django 5.2.1 on 2025-06-09 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_group_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='group_name',
        ),
        migrations.AddField(
            model_name='client',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='accounts.group', to_field='group_id'),
        ),
    ]
