# Generated by Django 5.2.1 on 2025-06-09 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(max_length=20, unique=True)),
                ('mode', models.CharField(choices=[('data_entry', 'Data Entry'), ('verification', 'Verification'), ('approval', 'Approval')], default='data_entry', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('months', models.CharField(max_length=100)),
                ('received_date', models.DateField()),
                ('from_date', models.DateField()),
                ('last_date', models.DateField()),
                ('alloted_date', models.DateField(blank=True, null=True)),
                ('done_date', models.DateField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('received_by', models.CharField(max_length=100)),
                ('alloted_to', models.CharField(blank=True, max_length=100, null=True)),
                ('query', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.accountbank')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_entries', to='accounts.client')),
            ],
            options={
                'verbose_name_plural': 'Data Entries',
            },
        ),
    ]
