# Generated by Django 5.2.1 on 2025-06-09 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_dataentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.user'),
        ),
    ]
