# Generated by Django 5.2.1 on 2025-06-09 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_dataentry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataentry',
            name='user',
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='alloted_to',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
