# Generated by Django 5.2.1 on 2025-06-09 14:08

import accounts.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_dataentry_user_alter_dataentry_alloted_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataentry',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='dataentry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dataentry',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='dataentry',
            name='months',
        ),
        migrations.RemoveField(
            model_name='dataentry',
            name='received_date',
        ),
        migrations.RemoveField(
            model_name='dataentry',
            name='trans_id',
        ),
        migrations.RemoveField(
            model_name='dataentry',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='dataentry',
            name='attach_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/clients/'),
        ),
        migrations.AddField(
            model_name='dataentry',
            name='format',
            field=models.CharField(choices=[('Soft Copy', 'Soft Copy'), ('Hard Copy', 'Hard Copy'), ('Link', 'Link')], default='Soft Copy', max_length=20),
        ),
        migrations.AddField(
            model_name='dataentry',
            name='is_nil',
            field=models.BooleanField(default=False, verbose_name='Nil'),
        ),
        migrations.AddField(
            model_name='dataentry',
            name='rec_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Received Date'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='alloted_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='from_date',
            field=models.DateField(default=accounts.models.get_first_day_of_last_month),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='last_date',
            field=models.DateField(default=accounts.models.get_last_day_of_last_month),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='query',
            field=models.CharField(choices=[('No', 'No'), ('Pending', 'Pending'), ('Done', 'Done')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='received_by',
            field=models.CharField(choices=[('Mail', 'Mail'), ('Acstkameet', 'Acstkameet'), ('WhatsApp', 'WhatsApp'), ('Anydesk', 'Anydesk')], default='Mail', max_length=20),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Nil', 'Nil'), ('Hold', 'Hold')], max_length=20),
        ),
    ]
