# Generated by Django 5.2.1 on 2025-06-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_dataentry_balance_remove_dataentry_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='attach_file',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
