# Generated by Django 5.2.1 on 2025-06-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_rename_user_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='virtual_account_type',
            field=models.CharField(blank=True, choices=[('1', 'Sales'), ('2', 'Purchase')], max_length=2, null=True),
        ),
    ]
