# Generated by Django 5.2.1 on 2025-06-13 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_dataentry_virtual_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cancel_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='gst_data',
            field=models.CharField(blank=True, choices=[('Direct', 'Direct'), ('Busy', 'Busy')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='gst_scheme',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Composition', 'Composition')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='period',
            field=models.CharField(blank=True, choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='reg_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='sale_define',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Cancelled', 'Cancelled'), ('Past', 'Past')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='timestamp',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='trade_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
