# Generated by Django 5.2.1 on 2025-06-13 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.bank'),
        ),
    ]
