# Generated by Django 5.2.1 on 2025-06-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_client_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='return_types',
        ),
        migrations.AddField(
            model_name='client',
            name='gst_return',
            field=models.BooleanField(default=False, verbose_name='GST'),
        ),
        migrations.AddField(
            model_name='client',
            name='it_return',
            field=models.BooleanField(default=False, verbose_name='Income Tax'),
        ),
        migrations.AddField(
            model_name='client',
            name='tcs_return',
            field=models.BooleanField(default=False, verbose_name='TCS'),
        ),
        migrations.AddField(
            model_name='client',
            name='tds_return',
            field=models.BooleanField(default=False, verbose_name='TDS'),
        ),
    ]
