# Generated by Django 5.2.1 on 2025-06-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_client_return_types_client_gst_return_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
