# Generated by Django 5.2.1 on 2025-06-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_client_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mobile_no',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
