# Generated by Django 5.2.1 on 2025-06-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_client_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='msg_id',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
