# Generated by Django 5.2.1 on 2025-06-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_dataentry_msg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='attach_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='attachments/'),
        ),
    ]
