# Generated by Django 5.2.1 on 2025-06-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_dataentry_attach_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='msg_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
