# Generated by Django 5.2.1 on 2025-06-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_dataentry_msg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='alloted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='last_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='rec_date',
            field=models.DateField(blank=True, null=True, verbose_name='Received Date'),
        ),
    ]
