# Generated by Django 5.2.1 on 2025-06-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_dataentry_alloted_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='query',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Pending', 'Pending'), ('Done', 'Done')], max_length=20, null=True),
        ),
    ]
