# Generated by Django 5.2.1 on 2025-06-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_dataentry_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='suspend_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
