# Generated by Django 5.2.1 on 2025-06-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_client_suspend_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='suspend_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
