# Generated by Django 5.2.1 on 2025-06-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_group_suspend_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbank',
            name='bank_mail_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='accountbank',
            name='branch_mail_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='accountbank',
            name='branch_mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='accountbank',
            name='cif_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accountbank',
            name='closing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountbank',
            name='reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountbank',
            name='statement_frequency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
