# Generated by Django 5.2.1 on 2025-06-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_accountbank_bank_mail_id_accountbank_branch_mail_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbank',
            name='stms_pws',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='accountbank',
            name='data_entry',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Import', 'Import')], default='Manual', max_length=20),
        ),
    ]
