# Generated by Django 5.2.1 on 2025-06-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_accountbank_stms_pws_alter_accountbank_data_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbank',
            name='busyacccode',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
