# Generated by Django 5.2.1 on 2025-06-30 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_accountbank_busyacccode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.accountbank'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='alloted_to',
            field=models.ForeignKey(blank=True, db_constraint=False, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userdata'),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='client',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='data_entries', to='accounts.client'),
        ),
    ]
