# Generated by Django 5.2.1 on 2025-07-01 14:15

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_dataentry_account_alter_dataentry_alloted_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='attach_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=accounts.models.upload_to),
        ),
    ]
