# Generated by Django 5.2.1 on 2025-07-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_dataentry_attach_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='status',
            field=models.CharField(blank=True, choices=[('Done', 'Done'), ('Nil', 'Nil'), ('Hold', 'Hold')], max_length=20, null=True),
        ),
    ]
