# Generated by Django 5.2.1 on 2025-07-24 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_taxsuspension'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='audit_status',
            field=models.CharField(blank=True, choices=[('Not Applicable', 'Not Applicable'), ('Audit', 'Audit'), ('Audit as Partnership', 'Audit as Partnership')], max_length=30, null=True, verbose_name='Audit Status'),
        ),
        migrations.AddField(
            model_name='client',
            name='it_alloted_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userdata'),
        ),
        migrations.AddField(
            model_name='client',
            name='it_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Income Tax Work Start Date'),
        ),
    ]
