# Generated by Django 5.2.1 on 2025-07-25 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_client_audit_status_client_it_alloted_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeTaxReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], max_length=9)),
                ('audit_applicable', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('ca', models.CharField(max_length=100)),
                ('audit_stage', models.CharField(blank=True, choices=[('Not Started', 'Not Started'), ('Started', 'Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20, null=True)),
                ('audit_status', models.CharField(choices=[('Active', 'Active'), ('Hold', 'Hold')], default='Active', max_length=6)),
                ('audit_hold_reason', models.TextField(blank=True, null=True)),
                ('audit_ack', models.CharField(blank=True, max_length=50, null=True)),
                ('audit_date', models.DateField(blank=True, null=True)),
                ('return_type', models.CharField(choices=[('Original', 'Original'), ('Revised', 'Revised')], max_length=10)),
                ('revise_no', models.PositiveIntegerField(blank=True, null=True)),
                ('stage', models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Filed', 'Filed'), ('Verified', 'Verified')], max_length=20, null=True)),
                ('return_status', models.CharField(choices=[('Active', 'Active'), ('Hold', 'Hold')], default='Active', max_length=6)),
                ('return_hold_reason', models.TextField(blank=True, null=True)),
                ('ack_no', models.CharField(blank=True, max_length=50, null=True)),
                ('ack_date', models.DateField(blank=True, null=True)),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alloted_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userdata')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_tax_returns', to='accounts.client')),
            ],
            options={
                'verbose_name': 'Income Tax Return',
                'verbose_name_plural': 'Income Tax Returns',
                'unique_together': {('year', 'client', 'return_type', 'revise_no')},
            },
        ),
    ]
