# Generated by Django 5.2.1 on 2025-07-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_incometaxreturn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incometaxreturn',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='incometaxreturn',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='incometaxreturn',
            name='audit_applicable',
            field=models.CharField(choices=[('as partner', 'as partner'), ('as a firm', 'as a firm'), ('audit applicable', 'audit applicable'), ('not applicable', 'not applicable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='incometaxreturn',
            name='return_type',
            field=models.CharField(choices=[('Original', 'Original'), ('Revised', 'Revised'), ('Rectified', 'Rectified'), ('Updated', 'Updated')], max_length=10),
        ),
        migrations.AlterField(
            model_name='incometaxreturn',
            name='revise_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incometaxreturn',
            name='year',
            field=models.DateField(verbose_name='Financial Year Start Date'),
        ),
    ]
