# Generated by Django 5.2.1 on 2025-07-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_remove_incometaxreturn_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometaxreturn',
            name='revise_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
