# Generated by Django 5.2.1 on 2025-07-25 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_incometaxreturn_revise_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometaxreturn',
            name='alloted_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userdata'),
        ),
        migrations.AlterField(
            model_name='incometaxreturn',
            name='client',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='income_tax_returns', to='accounts.client'),
        ),
    ]
