# Generated by Django 5.2.1 on 2025-07-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_alter_incometaxreturn_alloted_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometaxreturn',
            name='stage',
            field=models.CharField(blank=True, choices=[('Sleeping', 'Sleeping'), ('Call for data"', 'Call for data"'), ('Working', 'Working'), ('Query to client', 'Query to client'), ('Pending for checking', 'Pending for checking'), ('Pending for approve', 'Pending for approve'), ('Pending for filing', 'Pending for filing')], max_length=20, null=True),
        ),
    ]
