# Generated by Django 5.2.1 on 2025-07-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_incometaxreturn_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometaxreturn',
            name='ca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
