# Generated by Django 5.2.1 on 2025-07-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_alter_incometaxreturn_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometaxreturn',
            name='audit_stage',
            field=models.CharField(blank=True, choices=[('Audit Sent', 'Audit Sent'), ('Query From Audit', 'Query From Audit'), ('Audit Received', 'Audit Received'), ('Audit Checked', 'Audit Checked'), ('Audit Filled', 'Audit Filled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='incometaxreturn',
            name='stage',
            field=models.CharField(blank=True, choices=[('Sleeping', 'Sleeping'), ('Call for data"', 'Call for data"'), ('Working', 'Working'), ('Query to client', 'Query to client'), ('Pending for checking', 'Pending for checking'), ('Pending for approve', 'Pending for approve'), ('Pending for audit sent', 'Pending for audit sent'), ('audit sent', 'audit sent'), ('Pending for filing', 'Pending for filing'), ('Filed', 'Filed')], max_length=80, null=True),
        ),
    ]
