# Generated by Django 5.2.1 on 2025-07-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_alter_incometaxreturn_audit_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometaxreturn',
            name='audit_applicable',
            field=models.CharField(choices=[('as partner', 'as partner'), ('audit applicable', 'audit applicable'), ('not applicable', 'not applicable')], max_length=20),
        ),
    ]
