# Generated by Django 5.2.1 on 2025-07-30 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_alter_incometaxreturn_audit_applicable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='client',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_entries', to='accounts.client'),
        ),
    ]
