# Generated by Django 5.2.1 on 2025-07-30 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_alter_dataentry_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometaxreturn',
            name='client',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='income_tax_returns', to='accounts.client'),
        ),
    ]
