# Generated by Django 5.2.1 on 2025-08-02 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_alter_incometaxreturn_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(upload_to='ais_uploads/')),
                ('category', models.CharField(max_length=100)),
                ('reported_on', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('is_final_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.accountbank'),
        ),
    ]
