# Generated by Django 5.2.1 on 2025-08-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_aisrecord_alter_dataentry_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleSecurityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField()),
                ('date_of_sale', models.DateField()),
                ('security_name', models.TextField()),
                ('security_class', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('sale_price', models.FloatField()),
                ('sales_consideration', models.FloatField()),
                ('cost_of_acquisition', models.FloatField(blank=True, null=True)),
                ('fair_market_value', models.FloatField(blank=True, null=True)),
                ('indexed_cost', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
