# Generated by Django 5.2.1 on 2025-08-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_salesecurityrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesecurityrecord',
            name='assest_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
