# Generated by Django 5.2.1 on 2025-08-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_salesecurityrecord_assest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesecurityrecord',
            name='information_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
