# Generated by Django 5.2.1 on 2025-08-06 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_salesecurityrecord_information_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('information_code', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('source', models.TextField()),
                ('count', models.IntegerField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='SaleSecurityRecord',
        ),
        migrations.RenameField(
            model_name='aisrecord',
            old_name='description',
            new_name='data_json',
        ),
        migrations.RemoveField(
            model_name='aisrecord',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='aisrecord',
            name='category',
        ),
        migrations.RemoveField(
            model_name='aisrecord',
            name='is_final_approved',
        ),
        migrations.RemoveField(
            model_name='aisrecord',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='aisrecord',
            name='reported_on',
        ),
        migrations.RemoveField(
            model_name='aisrecord',
            name='status',
        ),
        migrations.RemoveField(
            model_name='aisrecord',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='aisrecord',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='accounts.aisupload'),
        ),
    ]
