# Generated by Django 5.2.1 on 2025-08-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_aisupload_delete_salesecurityrecord_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AISRecord',
        ),
        migrations.DeleteModel(
            name='AISUpload',
        ),
    ]
