# Generated by Django 5.2.1 on 2025-08-06 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_aisupload_aisrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AISRecord',
        ),
    ]
