# Generated by Django 5.2.1 on 2025-08-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_aisrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aisupload',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='aisrecord',
            name='section_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
