# Generated by Django 5.2.1 on 2025-08-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_remove_aisupload_uploaded_at_aisrecord_section_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisupload',
            name='total_records',
            field=models.IntegerField(default=0),
        ),
    ]
