# Generated by Django 5.2.1 on 2025-08-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_aisupload_total_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisupload',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
