# Generated by Django 5.2.1 on 2025-08-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_alter_aisupload_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='incometaxreturn',
            name='flag',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='incometaxreturn',
            name='rectification_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Filed', 'Filed')], max_length=7),
        ),
        migrations.AddField(
            model_name='incometaxreturn',
            name='revised_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Filed', 'Filed')], max_length=7),
        ),
        migrations.AddField(
            model_name='incometaxreturn',
            name='want_rectified',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AddField(
            model_name='incometaxreturn',
            name='want_revised',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='incometaxreturn',
            name='stage',
            field=models.CharField(blank=True, choices=[('Sleeping', 'Sleeping'), ('Call for data', 'Call for data'), ('Working', 'Working'), ('Query to client', 'Query to client'), ('Pending for checking', 'Pending for checking'), ('Pending for approve', 'Pending for approve'), ('Pending for audit sent', 'Pending for audit sent'), ('audit sent', 'audit sent'), ('Pending for filing', 'Pending for filing'), ('Filed', 'Filed')], max_length=80, null=True),
        ),
    ]
