# Generated by Django 5.2.1 on 2025-09-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_incometaxreturn_flag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_dat', models.DateTimeField()),
                ('sender_mail', models.EmailField(max_length=254)),
                ('receiver_mail', models.TextField()),
                ('subject', models.TextField(blank=True, default='')),
                ('attachment', models.BooleanField(default=False)),
                ('msg_id', models.CharField(max_length=255, unique=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
