# Generated by Django 5.2.1 on 2025-09-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_maillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='maillog',
            name='mailbox',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='maillog',
            unique_together={('mailbox', 'msg_id')},
        ),
    ]
