# Generated by Django 5.2.1 on 2025-09-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_maillog_mailbox_alter_maillog_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maillog',
            name='attachment',
        ),
        migrations.AddField(
            model_name='maillog',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='maillog',
            name='msg_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='maillog',
            index=models.Index(fields=['mailbox', 'rec_dat'], name='accounts_ma_mailbox_e4e1da_idx'),
        ),
        migrations.AddIndex(
            model_name='maillog',
            index=models.Index(fields=['rec_dat'], name='accounts_ma_rec_dat_d0a8af_idx'),
        ),
        migrations.AddIndex(
            model_name='maillog',
            index=models.Index(fields=['msg_id'], name='accounts_ma_msg_id_c5e025_idx'),
        ),
    ]
