# Generated by Django 5.2.1 on 2025-10-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_remove_maillog_attachment_maillog_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='extra_emails',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='group',
            name='extra_emails',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
