# Generated by Django 5.2.1 on 2025-11-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_client_extra_emails_group_extra_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbank',
            name='account_group',
            field=models.CharField(blank=True, choices=[('Bank Accounts', 'Bank Accounts'), ('Credit Card', 'Credit Card')], max_length=100),
        ),
    ]
