# Generated by Django 5.2.1 on 2025-11-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_alter_accountbank_account_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='status',
            field=models.CharField(blank=True, choices=[('Done', 'Done'), ('Nil', 'Nil'), ('Hold', 'Hold'), ('Pending', 'Pending')], max_length=20, null=True),
        ),
    ]
