# Generated by Django 5.2.1 on 2025-12-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_pdfconvertfailure'),
    ]

    operations = [
        migrations.AddField(
            model_name='maillog',
            name='statement_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
