# Generated by Django 5.2.1 on 2025-12-26 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_maillog_statement_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbank',
            name='account_group',
            field=models.CharField(blank=True, choices=[('Bank Accounts', 'Bank Accounts'), ('Credit Card', 'Credit Card'), ('Bank O/D Account', 'Bank O/D Account')], max_length=100),
        ),
        migrations.CreateModel(
            name='PendingBusyBankMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busy_company_code', models.CharField(db_index=True, help_text='Client.busy_code', max_length=20)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_no', models.CharField(db_index=True, max_length=50)),
                ('ifsc', models.CharField(blank=True, max_length=20, null=True)),
                ('swift', models.CharField(blank=True, max_length=20, null=True)),
                ('fy', models.CharField(db_index=True, max_length=7)),
                ('busy_updated_at', models.DateTimeField(help_text='Last modified datetime of BUSY .bds file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_busy_banks', to='accounts.client')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.group')),
            ],
            options={
                'db_table': 'pending_busy_bank_mapping',
                'ordering': ['client__client_name', 'fy', 'bank_name'],
                'indexes': [models.Index(fields=['busy_company_code'], name='pending_bus_busy_co_f46ba5_idx'), models.Index(fields=['fy'], name='pending_bus_fy_d1ade5_idx'), models.Index(fields=['account_no'], name='pending_bus_account_3278a2_idx')],
                'unique_together': {('client', 'account_no', 'fy')},
            },
        ),
    ]
