# Generated by Django 5.2.1 on 2025-12-27 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_alter_accountbank_account_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingbusybankmapping',
            name='busy_company_code',
            field=models.CharField(help_text='Client.busy_code', max_length=20),
        ),
        migrations.AlterField(
            model_name='pendingbusybankmapping',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.group'),
        ),
    ]
