# Generated by Django 5.2.1 on 2025-12-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_alter_pendingbusybankmapping_busy_company_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingbusybankmapping',
            name='busy_account_code',
            field=models.CharField(blank=True, help_text='Account code from BUSY', max_length=100, null=True),
        ),
    ]
