# Generated by Django 5.2.1 on 2026-01-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0073_pendingbusybankmapping_busy_account_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbank',
            name='account_id',
            field=models.IntegerField(unique=True),
        ),
    ]
