# Generated by Django 5.2.1 on 2026-01-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0074_alter_accountbank_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbank',
            name='account_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
