# Generated by Django 5.2.1 on 2026-01-06 10:26

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0075_alter_accountbank_account_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('annual_allowed', models.BooleanField(default=False)),
                ('event_allowed', models.BooleanField(default=False)),
                ('continue_till_closed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ClientDocItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_kind', models.CharField(choices=[('ANNUAL', 'Annual'), ('EVENT', 'Event')], max_length=10)),
                ('financial_year', models.CharField(blank=True, default='', max_length=7)),
                ('event_name', models.CharField(blank=True, default='', max_length=120)),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received'), ('NA', 'Not Applicable')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_items', to='accounts.client')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.doccategory')),
            ],
        ),
        migrations.CreateModel(
            name='ClientDocFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=accounts.models.client_document_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_password', models.CharField(blank=True, default='', max_length=80)),
                ('password_validity_year', models.CharField(blank=True, default='', max_length=7)),
                ('carry_password_forward', models.BooleanField(default=False)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, db_constraint=False,)),
                ('doc_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='accounts.clientdocitem')),
            ],
        ),
        migrations.CreateModel(
            name='DocPasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=80)),
                ('validity_year', models.CharField(blank=True, default='', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL,db_constraint=False,)),
                ('doc_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to='accounts.clientdocitem')),
            ],
        ),
        migrations.CreateModel(
            name='DocSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtypes', to='accounts.doccategory')),
            ],
            options={
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='clientdocitem',
            name='subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.docsubtype'),
        ),
        migrations.AddIndex(
            model_name='clientdocitem',
            index=models.Index(fields=['client', 'financial_year', 'status'], name='accounts_cl_client__b199e5_idx'),
        ),
        migrations.AddIndex(
            model_name='clientdocitem',
            index=models.Index(fields=['client', 'doc_kind', 'status'], name='accounts_cl_client__592978_idx'),
        ),
    ]
