# Generated by Django 5.2.1 on 2026-01-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0076_doccategory_clientdocitem_clientdocfile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdocfile',
            name='uploaded_by',
        ),
    ]
