# Generated by Django 5.2.1 on 2026-01-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_remove_clientdocfile_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='doccategory',
            name='category_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
