# Generated by Django 5.2.1 on 2026-01-09 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0078_doccategory_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doccategory',
            name='name',
        ),
    ]
