# Generated by Django 5.2.1 on 2026-01-09 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0079_remove_doccategory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientWiseCategoryName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Rajendra Prasad, Rakesh Shah', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_category_names', to='accounts.doccategory')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_names', to='accounts.client')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('client', 'category', 'name')},
            },
        ),
    ]
