# Generated by Django 5.2.1 on 2026-01-09 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0080_clientwisecategoryname'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocitem',
            name='category_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.clientwisecategoryname'),
        ),
    ]
