# Generated by Django 5.2.1 on 2026-01-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0081_clientdocitem_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocitem',
            name='data_entry_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('HOLD', 'Hold'), ('DONE_NO_RECEIVE', 'Done without Received')], default='PENDING', max_length=20),
        ),
    ]
