# Generated by Django 5.2.1 on 2026-01-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0082_clientdocitem_data_entry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientwisecategoryname',
            name='passwords',
            field=models.TextField(blank=True, default='', help_text='Comma-separated passwords (optional)'),
        ),
    ]
