# Generated by Django 5.2.1 on 2026-01-16 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0083_clientwisecategoryname_passwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdocitem',
            name='subtype',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.docsubtype'),
        ),
    ]
