# Generated by Django 5.2.1 on 2026-01-16 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0084_alter_clientdocitem_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdocitem',
            name='category',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='accounts.doccategory'),
        ),
        migrations.AlterField(
            model_name='clientdocitem',
            name='category_name',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.clientwisecategoryname'),
        ),
        migrations.AlterField(
            model_name='clientdocitem',
            name='client',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='doc_items', to='accounts.client'),
        ),
    ]
